name: Deploy Static Website (Terraform)

on:
  push:
    branches: [main]
    paths:
      - "src/front/**"
      - "environments/s3.tf"
  workflow_dispatch:

env:
  AWS_REGION: il-central-1

permissions:
  id-token: write
  contents: read

jobs:
  static-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::423408880404:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_OIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: STS who-am-I
        run: aws sts get-caller-identity

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform apply (S3 site only)
        working-directory: environments
        run: |
          terraform init
          terraform apply \
            -target=aws_s3_object.index \
            -target=aws_s3_object.css \
            -target=aws_s3_object.visitor_js \
            -auto-approve
