name: Deploy Lambda (Terraform)

on:
  push:
    branches: [main]
    paths:
      - "src/back/**"
      - "environments/lambda.tf"
  workflow_dispatch:

env:
  AWS_REGION: il-central-1

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requirements (if any)
        run: |
          if [ -f src/back/requirements.txt ]; then
            pip install -r src/back/requirements.txt
          fi

      - name: Compile Lambda source
        run: python -m py_compile src/back/lambda_function.py

  deploy:
    needs: build            
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::423408880404:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_OIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform apply (lambda only)
        working-directory: environments
        run: |
          terraform init
          terraform apply \
            -target=aws_lambda_function.lambda \
            -auto-approve

